import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/Provider/ThemeProvider";
import { ToastContainer } from 'react-toastify';
import { PortfolioProvider } from "@/context/PortfolioContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dynamic Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ToastContainer />
          <PortfolioProvider>
          <div className="min-h-screen bg-background">
            <Header />
            <main className="container max-w-7xl mx-auto px-4 py-6 space-y-6">
              {children}
            </main>
          </div>
          </PortfolioProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
